import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/app/components/Nav";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div
          className="
            mx-auto w-full px-4 sm:px-6 lg:px-8 py-4
            grid grid-cols-1 gap-4
            lg:grid-cols-[285px_minmax(0,1fr)_285px] lg:gap-6
            bg-[#ffe5d9]
            min-h-screen
          "
        >
          <div>
            <NavBar />
          </div>
          <main className="min-w-0 min-h-screen">
            <div className="mx-auto w-full max-w-3xl">{children}</div>
          </main>
          <div className="hidden lg:block" />
        </div>
      </body>
    </html>
  );
}
